config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'cocktails#index'
  get 'search', to: 'cocktails#search'

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :cocktails, only: [ :index ]
    end
  end
  
  resources :cocktails, only: [ :index, :create, :show, :search, :update ] do
    resources :reviews, only: [ :new, :create, :index ]
    resources :doses, only: [ :new, :create ]
  end

  resources :doses, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
    has_many :doses, dependent: :destroy
    #has_many :ingredients, through: :doses, dependent: :destroy
    has_many :measures, through: :doses, dependent: :destroy
    has_one_attached :photo, dependent: :destroy
    has_many :reviews, dependent: :destroy
    belongs_to :user

    validates :name, uniqueness: true, presence: true
    validates :user, presence: true
    validates :photo, presence: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :measure

  
  #validates :cocktail, uniqueness: { scope: :ingredient }
  #validates :ingredient, uniqueness: { scope: :cocktail }, presence: true
  validates :amount, presence: true
  validates :measure, presence: true
  validates :ingredient, presence: true, uniqueness: { scope: :cocktail }
end

app/models/measure.rb
class Measure < ApplicationRecord
    has_many :doses

    validates :unit, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :cocktail
  belongs_to :user

  validates :user, uniqueness: { scope: :cocktail }, presence: true
  validates :cocktail, presence: true
  validates :content, presence: true
  validates :rating, presence:true, inclusion: { in: (1..5) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cocktails
  has_many :reviews
end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ActionController::API
    rescue_from ActiveRecord::RecordNotFound, with: :not_found
  
    private
  
    def not_found(exception)
      render json: { error: exception.message }, status: :not_found
    end
end

app/controllers/api/v1/cocktails_controller.rb
class Api::V1::CocktailsController < Api::V1::BaseController
    def index
      @cocktails = Cocktail.all
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :resource_name, :resource, :devise_mapping, :resource_class
    def resource_name
      :user
    end
     
    def resource
      @resource ||= User.new
    end
  
    def resource_class
      User
    end
     
    def devise_mapping
      @devise_mapping ||= Devise.mappings[:user]
    end
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
    before_action :set_cocktail, only: [:show, :update]
    before_action :authenticate_user!, only: [:create]
    
    def index
        @cocktails = Cocktail.all
        @cocktail = Cocktail.new
    end
    
    def create
        @cocktail = Cocktail.new(cocktail_params)
        @cocktail.user = current_user

        if @cocktail.save
            redirect_to cocktail_path(@cocktail)
        else
            redirect_to root_path
        end
    end

    def show
        @dose = Dose.new
        @review = Review.new
    end

    def search
        if params[:params][:query].present?
            sql_query = " \
                cocktails.name @@ :query \
                OR doses.ingredient @@ :query \
            "

            @cocktails = Cocktail.joins(:doses).where(sql_query, query: "%#{params[:params][:query]}%").uniq
        else
            @cocktails = Cocktail.all
        end
    end
    
    def update
        @cocktail.update(cocktail_params)

        redirect_to cocktail_path(@cocktail)
    end

    private

    def set_cocktail
        @cocktail = Cocktail.find(params[:id])
    end

    def cocktail_params
        params.require(:cocktail).permit(:name, :doses, :photo, :instructions)
    end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
    def create 
        @cocktail = Cocktail.find(params[:cocktail_id])       
        @dose = Dose.new(dose_params)
        @dose.cocktail = @cocktail
        @dose.save
        
        redirect_to cocktail_path(@cocktail)
    end

    def destroy
        @dose = Dose.find(params[:id])
        @dose.destroy

        redirect_to cocktail_path(@dose.cocktail)
    end

    private

    def dose_params
        params.require(:dose).permit(:amount, :ingredient, :cocktail_id, :measure_id)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :authenticate_user!, only: [:create]
    def create 
        @cocktail = Cocktail.find(params[:cocktail_id])       
        @review = Review.new(review_params)
        @review.cocktail = @cocktail
        @review.user = current_user
        @review.save
        
        redirect_to cocktail_path(@cocktail)
    end

    def index
        @reviews = Review.where(cocktail: params[:cocktail_id])
        @cocktail = Cocktail.find(params[:cocktail_id])
    end

    private

    def review_params
        params.require(:review).permit(:content, :rating)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/cocktails/index.html.erb
<nav class="homepage">
    <%= render 'shared/navbar' %>
</nav>

<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img class="d-block w-100" src="https://res.cloudinary.com/maiteeguren/image/upload/v1608541784/645243489f8808bcbff096e1819a762f_oy3eix.png" alt="First slide">
            <!--
            <img class="d-block w-100" src="https://www.mensjournal.com/wp-content/uploads/2015/05/frozen-cocktails.jpg?quality=86&strip=all" alt="First slide">
            
            <div class="carousel-caption d-none d-md-block">
                <h5>Discover your new favorite cocktail recipe</h5>
                <p>Learn how to make a classic drink right at home.</p>
            </div>
            -->
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="https://res.cloudinary.com/maiteeguren/image/upload/v1608542724/bd16955414f17dd1830fcad3afff6309_fzlktw.jpg" alt="Second slide">
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="https://res.cloudinary.com/maiteeguren/image/upload/v1608766342/Article-Lychee-Martini-90s-cocktail_hnqg2s.jpg"  alt="Third slide">
        </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="ingredients-section">
    <div class="text-box h-100">
        <h2 class="w-100">Lorem ipsum</h2>
        
        <div class="cards-container">
            <div class="value-card">
                <h3>Lorem ipsum dolor sit amet</h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
            </div>

            <div class="value-card">
                <h3>Lorem ipsum dolor sit amet</h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
            </div>

            <div class="value-card">
                <h3>Lorem ipsum dolor sit amet</h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
            </div>
        </div>
    </div>
    <img class="lemon-slice" src="https://res.cloudinary.com/maiteeguren/image/upload/v1608635314/l-stock-photo-fresh-lemon-slice-close-up-on-bright-blue-background-flat-lay-summer-concept-673602406-removebg-preview_rkobrw.png">
    <div class="image-shadow h-100">
        <img class="ingredients-img h-100"src="https://res.cloudinary.com/maiteeguren/image/upload/v1608761714/Drinks-0022_pyg7ka.jpg">
    </div>
    <img class="rosemary" src="https://cdn.webshopapp.com/shops/255487/themes/167883/assets/ingredient-rosemary.png?2020121617062820201216170932">
</div>

<div class="grid-container" id="cocktails">
    <div>
        <h2>Recipes</h2>
    </div>
    <div class="card-columns">
        <%  @cocktails.shuffle.each do |cocktail|  %>
            <a href="<%= cocktail_path(cocktail)%>">
                <div class="photo">
                    <%= cl_image_tag cocktail.photo.key, width: 270, crop: :fill unless cocktail.nil? %>
                    <div class="overlay">
                        <h5 class="title"><%= cocktail.name %></h5>
                    </div>
                </div>
            </a>
        <% end %>
    </div>
</div>

<footer class="parallax">
    <h2>Footer</h2>
</footer>

app/views/cocktails/search.html.erb
<nav class="sticky">
    <%= render 'shared/navbar' %>
</nav>
<div class="show-container">
    <%= link_to '<< BACK', root_path, class:"btn btn-back" %>

    <div class="search-results">
        <h2 class="grey grey-underline">Search results for "<%= params[:params][:query] %>"</h2>

        <div class="search-grid">
            <%  @cocktails.each do |cocktail|  %>
                <div class="card" style="width: 18rem;">
                    <a href="<%= cocktail_path(cocktail)%>" class="cocktail-link"></a>
                    <%= cl_image_tag cocktail.photo.key, class:"card-img-top", crop: :fill unless cocktail.nil? %>
                    <div class="card-body">
                        <h5 class="card-title grey"><%= cocktail.name %></h5>
                        <p class="card-text grey">
                            <% ingredients = ""%>
                            <% cocktail.doses.each do |dose| %>
                                <% if dose === cocktail.doses.first %>
                                    <% ingredients << dose.ingredient %>
                                <% elsif  dose === cocktail.doses.last %>
                                    <% ingredients << " & #{dose.ingredient}." %>
                                <% else %>
                                    <% ingredients << ", #{dose.ingredient}" %>
                                <% end %>
                            <% end %>
                            <%= ingredients.capitalize %>
                        </p>
                        <a href="<%= cocktail_path(cocktail)%>" class="btn btn-grey">See Recipe</a>
                    </div>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/cocktails/show.html.erb
<nav class="sticky">
    <%= render 'shared/navbar' %>
</nav>

<div class="show-container">
    <%= link_to '<< BACK', root_path, class:"btn btn-back" %>
    <div class="cocktail-card">
      
        <%= cl_image_tag @cocktail.photo.key, width: 400, class: "cocktail-image" %>  
        <div class="cocktail-info">
            <div class="d-flex justify-content-between grey-underline">
                <h2 class="grey m-0 text-left"><%= @cocktail.name %></h2>
                <% if @cocktail.reviews.length > 0 %>
                    <% ratingCount = 0 %>
                    <% @cocktail.reviews.each do |review| %>
                        <% ratingCount += review.rating %>
                    <% end %>
                    <% ratingAverage = ratingCount / @cocktail.reviews.length %>
                    <div class="d-flex align-items-center justify-content-end stars-box">
                        <% ratingAverage.times do %> 
                            <img src="https://img.icons8.com/fluent/48/000000/star.png" class="rating-icon"/>
                        <% end %>
                        <% if ratingAverage < 5 %>
                            <% ( 5 - ratingAverage).times do %> 
                            <img src="https://img.icons8.com/fluent/48/000000/star.png" class="rating-icon" style="opacity: 0.6; filter: grayscale(1);"/>                            
                            <% end %>
                        <% end %>
                        <a href="<%= cocktail_reviews_path(@cocktail) %>"><p class="my-0 ml-1 grey small-text"> (<%= @cocktail.reviews.length  %> <%= 'review'.pluralize(@cocktail.reviews.length) %>)</p></a>
                    </div>
                <% end %>
            </div>
            <p class="subtitle">Ingredients</p>
            <ul>
                <% @cocktail.doses.each do |dose| %>
                    <li class="d-flex align-items-center">
                        <p class="m-0"><%= dose.amount %> <%= dose.measure.unit %> <%= dose.ingredient %></p>
                        <% if @cocktail.user === current_user %>
                            <img src="https://res.cloudinary.com/maiteeguren/image/upload/v1608715767/img_216627_wyjfkh.png" width="10px" class="btn p-0" id="delete-ingredient" >
                            <%= link_to "", dose_path(dose), method: :delete, remote:true, id: "delete-ingredient-link", class: "hidden" %>
                        <% end %>
                    </li>
                <% end %>
                <% if @cocktail.user === current_user %>
                    <li class="d-block add-new-dose">
                        <div class="d-flex justify-content-between add-new-dose-icon">
                            <p class="btn btn-grey new-ingredient-btn" data-toggle="modal" data-target="#new-ingredient-modal">+ Add ingredient</p>
                        </div>
                    </li>
                <% end %>
            </ul>
            
            <p class="subtitle">Instructions</p>
            <p><%= @cocktail.instructions %></p>
            
            <% if @cocktail.reviews.length > 0 %>
                <a href="<%= cocktail_reviews_path(@cocktail) %>"><p class="subtitle">Reviews (<%= @cocktail.reviews.count %>)</p></a>
            <% else %>
                <p class="subtitle">Reviews (<%= @cocktail.reviews.count %>)</p>
            <% end %>
            
            <ul>
                <li class="d-block add-new-dose">
                    <div class="d-flex justify-content-between add-new-review">
                        <p class="btn btn-grey new-review-btn" data-toggle="modal" data-target="#new-review-modal">+ Add a review</p>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</div>

<%= render 'shared/ingredient-modal', cocktail: @cocktail, dose: @dose %>
<%= render 'shared/review-modal', cocktail: @cocktail, review: @review %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Miss Cocktail</title>
    <link rel="icon" href="https://res.cloudinary.com/maiteeguren/image/upload/v1608886750/cocktail_r9fm3g.png" type="image/icon type">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta property="og:image" content="https://res.cloudinary.com/maiteeguren/image/upload/v1608943361/Pink_and_Blue_Simple_Marketing_Strategy_Presentation_gavcxw.jpg">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@200;300&family=Open+Sans+Condensed:wght@300&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Rye&display=swap" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="/path/to/parallax.min.js"></script>
  </head>

  <body>
  
    <% if notice %>
      <div class="alert alert-success"><%= notice %></div>
    <% end %>
    <% if alert %>
      <div class="alert alert-warning"><%= alert %></div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/reviews/index.html.erb
<div class="reviews-container">
    <div class="title-container">
        <h2 class="grey"><%= @cocktail.name %></h2>
        <% if @reviews.length > 0 %>
            <% ratingCount = 0 %>
            <% @reviews.each do |review| %>
                <% ratingCount += review.rating %>
            <% end %>
            <% ratingAverage = ratingCount / @reviews.length %>
            <div class="d-flex align-items-center">
                <% ratingAverage.times do %> 
                    <img src="https://img.icons8.com/fluent/48/000000/star.png" class="rating-icon"/>
                <% end %>
                <% if ratingAverage < 5 %>
                    <% ( 5 - ratingAverage).times do %> 
                    <img src="https://img.icons8.com/fluent/48/000000/star.png" class="rating-icon" style="opacity: 0.6; filter: grayscale(1);"/>                            
                    <% end %>
                <% end %>
                <p class="my-0 ml-1"> (<%= @reviews.length  %> <%= 'review'.pluralize(@reviews.length) %>)</p>
            </div>
        <% end %>
    </div>
    <ul>
        <% @reviews.each do |review| %>
            <li class="d-block">
                <p><b><%= review.user.name %></b></p>
                <p><%= review.created_at.strftime("%d %B %Y") %></p>
                <% review.rating.times do %> 
                    <img src="https://img.icons8.com/fluent/48/000000/star.png" class="rating-icon"/>
                <% end %>
                <% if review.rating < 5 %>
                    <% ( 5 - review.rating).times do %> 
                    <img src="https://img.icons8.com/fluent/48/000000/star.png" class="rating-icon" style="opacity: 0.6; filter: grayscale(1);"/>                            
                    <% end %>
                <% end %>
                <p class="review-content"><%= review.content %></p>
            </li>
        <% end %>
    </ul>
</div>
<div class="w-100 d-flex justify-content-center position-absolute b-40">
    <%= link_to '<< BACK', cocktail_path(@cocktail), class:"btn" %>
</div>

app/views/shared/_cocktail-modal.html.erb
<% if @cocktail %>
    <div class="modal fade" id="new-cocktail-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content p-5">
            <div class="modal-header">
                <h2>New cocktail</h2>
                <button type="button" class="close close-modal" data-dismiss="modal" aria-label="Close">
                    <img src="https://res.cloudinary.com/maiteeguren/image/upload/v1608715767/img_216627_wyjfkh.png" width="30px" class="close-modal">
                </button>
            </div>
            <div class="modal-body pt-2">
                <%= simple_form_for(@cocktail) do |f| %>
                    <div>
                        <%= f.input :name, label_html: { class:"btn m-0" }  %>
                        <%= f.input :instructions, as: :text, label_html: { class:"btn m-0" } %>
                        <label class="btn">
                        Add a photo
                        <span style="display:none;">
                            <%= f.input :photo, as: :file %>
                        </span>
                        </label>
                    </div>
                    <%= f.button :submit, class: 'mx-auto btn btn-grey d-block' %>
                <% end %>
            </div>
        </div>
    </div>
    </div>
<% end %>

app/views/shared/_ingredient-modal.html.erb
<div class="modal fade" id="new-ingredient-modal" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content p-5">
        <div class="modal-header">
            <h2>New ingredient</h2>
            <button type="button" class="close close-modal" data-dismiss="modal" aria-label="Close">
                <img src="https://res.cloudinary.com/maiteeguren/image/upload/v1608715767/img_216627_wyjfkh.png" width="30px" class="close-modal">
            </button>
        </div>
        <div class="modal-body pt-2">
            <%= simple_form_for [@cocktail, @dose], remote:true do |f| %>
                <div class="form-inputs">
                    <div class="d-flex">
                        <%= f.input :amount, label_html: { class:"btn" } %>
                        <%= f.association :measure, label_method: :unit, label_html: { class:"btn" } %>
                    </div>
                    <%= f.input :ingredient, label_html: { class:"btn" } %>
                    <%= f.button :submit, class: "btn btn-grey mt-3" %>
                </div>
            <% end %>
        </div>
    </div>
  </div>
</div>

app/views/shared/_login_form.html.erb
<div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true" id="login-modal">
  <div class="modal-dialog modal-dialog-centered modal-lg">
    <div class="modal-content flex-row">
      <div class="w-50 p-5 pink-bg d-flex flex-column justify-content-center">

        <h5 class="modal-title text-center" id="exampleModalLabel">Log in</h5>
        <div>
          <%= simple_form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
            <div class=" p-0">
              <%= f.input :email,
                  required: false,
                  autofocus: true,
                  label_html: { autocomplete: "email", class:"btn white m-0" } %>
              <%= f.input :password,
                  required: false,
                  input_html: { autocomplete: "current-password" },
                  label_html: { class: "btn white m-0" } %>
              <%= f.input :remember_me, label_html: { class: "btn white m-0" }, as: :boolean if devise_mapping.rememberable? %>
            </div>
            <%= f.button :submit, "Log in", class: "btn btn-white my-0 mx-auto d-block" %>
            
          <% end %>
        </div>
      </div>
      <div class="w-50 p-5">
      
        <div class="">
          <h5 class="modal-title grey text-center">create a new account</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <img src="https://res.cloudinary.com/maiteeguren/image/upload/v1608715767/img_216627_wyjfkh.png" width="30px" class="close-modal">
          </button>
        </div>
        
        <div class="">
          <%= simple_form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
            <%= f.error_notification %>
            <div class="p-0">
              <%= f.input :name,
                          required: true,
                          autofocus: true,
                          input_html: { autocomplete: "email" },
                          label_html: { class: "btn m-0" } %>
              <%= f.input :email,
                          required: true,
                          autofocus: true,
                          input_html: { autocomplete: "email" },
                          label_html: { class: "btn m-0" } %>
              <%= f.input :password,
                          required: true,
                          hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length),
                          input_html: { autocomplete: "new-password" },
                          label_html: { class: "btn m-0" } %>
              <%= f.input :password_confirmation,
                          required: true,
                          input_html: { autocomplete: "new-password" },
                          label_html: { class: "btn m-0" } %>
            </div>
            <%= f.button :submit, "Sign up", class: "btn btn-grey my-0 mx-auto d-block" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="w-33">
    <div class="mobile-menu">
        <img src="https://res.cloudinary.com/maiteeguren/image/upload/v1608715767/345387-200_otkuq5.png" width="50px" id="menu-icon">
        <img src="https://res.cloudinary.com/maiteeguren/image/upload/v1608715767/img_216627_wyjfkh.png" width="30px" class="hidden" id="exit-icon">
    </div>
    <ul class="menu hide-menu">
        <li><a class="nav-item" href="<% root_path %>/#cocktails">All Recipes</a></li>
        <% if user_signed_in? %>
            <% if current_page?(root_path) %>
                <li><a class="nav-item" href="#" data-toggle="modal" data-target="#new-cocktail-modal">Add New Cocktail</a></li>
            <% elsif @cocktail.id && @cocktail.user === current_user %>
                <li><a class="nav-item" href="#" data-toggle="modal" data-target="#new-cocktail-modal">Edit Cocktail</a></li>
            <% end %>
        <% else %>
            <li><%= link_to "Add New Cocktail", "", class:"nav-item", data: {toggle: "modal", target: "#login-modal"} %></li>
        <% end %>
    </ul>
</div>
<div class="w-33 text-center">
    <a href="<%= root_path %>"><h1>Miss Cocktail</h1></a> 
</div>
<div class="w-33">
    <ul class="menu hide-menu justify-content-end">
        <li class="nav-item">
            <form novalidate="novalidate" class="simple_form search" action="/search" accept-charset="UTF-8" method="get"><input name="utf8" type="hidden" value="&#x2713;" />
                <div class="search-form-control form-group d-flex">
                    <input class="form-control string required" type="text" name="params[query]" id="search_query" placeholder="Search by name or ingredient..." />
                    <button name="button" type="submit" class="btn">Search</button>
                </div>
            </form>
        </li>

        <li class="d-flex align-items-center">
            <% if user_signed_in? %>
                <%= link_to "Logout", destroy_user_session_path, method: :delete, class:"nav-item log-in" %>
            <% else %>
                <%= link_to "Login", "", class:"nav-item log-in", data: {toggle: "modal", target: ".bd-example-modal-lg"} %>
            <% end %>
        </li>
    </ul>
</div>

<%= render 'shared/login_form' %>
<%= render 'shared/cocktail-modal' %>

app/views/shared/_review-modal.html.erb
<div class="modal fade" id="new-review-modal" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content p-5">
        <div class="modal-header">
            <h2>New review</h2>
            <button type="button" class="close close-modal" data-dismiss="modal" aria-label="Close">
                <img src="https://res.cloudinary.com/maiteeguren/image/upload/v1608715767/img_216627_wyjfkh.png" width="30px" class="close-modal">
            </button>
        </div>
        <div class="modal-body pt-2">
            <%= simple_form_for [@cocktail, @review] do |f| %>
                <div class="form-inputs">
                    <%= f.input :content, label_html: { class:"btn" }  %>
                    <%= f.input :rating, collection: 1..5, label_html: { class:"btn" }   %>
                    <%= f.button :submit, class: "btn btn-grey mt-3" %>
                </div>
            <% end %>
        </div>
    </div>
  </div>
</div>